### ISSUE TITLE
benchmark_batteries/stream.byte : Fatal error

### ISSUE THREAD

**Issue by Fourchaux** [strymonas/staged-streams.ocaml#3]
With  OCaml 4.02.1+BER - oasis 0.4.7 - ounit 2.0.0 - oml 0.0.5 - batteries 2.3.0 ( & Linux x86_64) :

Installing the program and running unit tests is OK.

Creating the benchmarks files seems correct. 
(modulo several Warnings 8 : this pattern-matching is not exhaustive !)

But running benchmark_batteries/stream.byte  gives : 

Benchmark                            Mean Mean-Error  Sdev    Unit
Fatal error: exception Sys_error("/tmpgen.ml: Permission denied")

Any hint ? Thank you.

**Comment by biboudis** [comment]
Yes indeed, I got that report from other users as well. It is related with the code generation function of the benchmark code and specifically of the `get_temp_dir_name` call that I use from the `Filename` module. Instead of providing a temporary solution I will provide a small fix tomorrow. Thank you for reporting @Fourchaux!

**Comment by biboudis** [comment]
@Fourchaux can you run the benchmarks now?

**Comment by Fourchaux** [comment]
I can run the benchmarks. Perfect.

I close this issue. 

ευχαριστώ

**Comment by biboudis** [comment]
Thx @Fourchaux for reporting!
